### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by smnogar** [tue-robotics/rgbd#7]
I am not sure if something in the build chain has changed, but using the newest docker image from osrf/ros kinetic-full I am getting build errors:

~~~
CMakeFiles/rgbd.dir/src/View.cpp.o: In function `main':
View.cpp:(.text+0x0): multiple definition of `main'
CMakeFiles/rgbd.dir/src/Server.cpp.o:Server.cpp:(.text+0x721): first defined here
collect2: error: ld returned 1 exit status
make[2]: *** [/build/devel/.private/rgbd/lib/librgbd.so] Error 1
make[1]: *** [CMakeFiles/rgbd.dir/all] Error 2
make: *** [all] Error 2
~~~

Removing say View.cpp from library rgbd in CMakeLists.txt results in linker errors. I am also getting linking errors in macOS.

**Comment by MatthijsBurgh** [comment]
At a first look, I am not able to find the real problem. I think it could be an possibility your compiler is ignoring the uppercase. This would be an explanation for having multiple definitions of main. Because in the lib shouldn't be any main functions, only in an executable.  Maybe @Timple or @reinzor have more knowledge to fix this issue.

@smnogar could you provide more information about your compiler etc.

**Comment by smnogar** [comment]
Sure, so I just got this to compile in a native ubuntu 16.04 install, but I can't get it to work in docker. I tested it in the docker image provided in tue-dev. Here is the output of build.cmake.log

~~~
Not searching for unused variables given on the command line.
[36m--[0m The C compiler identification is GNU 5.4.0
[36m--[0m The CXX compiler identification is GNU 5.4.0
[36m--[0m Check for working C compiler: /usr/bin/cc
[36m--[0m Check for working C compiler: /usr/bin/cc -- works
[36m--[0m Detecting C compiler ABI info
[36m--[0m Detecting C compiler ABI info - done
[36m--[0m Detecting C compile features
[36m--[0m Detecting C compile features - done
[36m--[0m Check for working CXX compiler: /usr/bin/c++
[36m--[0m Check for working CXX compiler: /usr/bin/c++ -- works
[36m--[0m Detecting CXX compiler ABI info
[36m--[0m Detecting CXX compiler ABI info - done
[36m--[0m Detecting CXX compile features
[36m--[0m Detecting CXX compile features - done
[36m--[0m Using CATKIN_DEVEL_PREFIX: /home/amigo/ros/kinetic/system/devel/.private/rgbd
[36m--[0m Using CMAKE_PREFIX_PATH: /home/amigo/ros/kinetic/system/devel;/opt/ros/kinetic;/home/amigo/ros/kinetic/dev/devel
[36m--[0m This workspace overlays: /home/amigo/ros/kinetic/system/devel;/opt/ros/kinetic
[36m--[0m Found PythonInterp: /usr/bin/python (found version "2.7.12")
[36m--[0m Using PYTHON_EXECUTABLE: /usr/bin/python
[36m--[0m Using Debian Python package layout
[36m--[0m Using empy: /usr/bin/empy
[36m--[0m Using CATKIN_ENABLE_TESTING: ON
[36m--[0m Call enable_testing()
[36m--[0m Using CATKIN_TEST_RESULTS_DIR: /home/amigo/ros/kinetic/system/build/rgbd/test_results
[36m--[0m Looking for pthread.h
[36m--[0m Looking for pthread.h - found
[36m--[0m Looking for pthread_create
[36m--[0m Looking for pthread_create - not found
[36m--[0m Looking for pthread_create in pthreads
[36m--[0m Looking for pthread_create in pthreads - not found
[36m--[0m Looking for pthread_create in pthread
[36m--[0m Looking for pthread_create in pthread - found
[36m--[0m Found Threads: TRUE
[36m--[0m Found gtest sources under '/usr/src/gtest': gtests will be built
[36m--[0m Using Python nosetests: /usr/bin/nosetests-2.7
[36m--[0m catkin 0.7.8
[36m--[0m Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
[36m--[0m rgbd: 1 messages, 2 services
[36m--[0m Configuring done
[36m--[0m Generating done
[36m--[0m Build files have been written to: /home/amigo/ros/kinetic/system/build/rgbd
~~~

and the output of make.log

~~~
[35m[1mScanning dependencies of target _rgbd_generate_messages_check_deps_Project2DTo3D[0m
[35m[1mScanning dependencies of target sensor_msgs_generate_messages_cpp[0m
[35m[1mScanning dependencies of target _rgbd_generate_messages_check_deps_RGBDMsg[0m
[35m[1mScanning dependencies of target std_msgs_generate_messages_cpp[0m
[  0%] Built target sensor_msgs_generate_messages_cpp
[35m[1mScanning dependencies of target geometry_msgs_generate_messages_cpp[0m
[  0%] Built target std_msgs_generate_messages_cpp
[  0%] Built target _rgbd_generate_messages_check_deps_RGBDMsg
[35m[1mScanning dependencies of target _rgbd_generate_messages_check_deps_GetRGBD[0m
[  0%] Built target _rgbd_generate_messages_check_deps_Project2DTo3D
[  0%] Built target geometry_msgs_generate_messages_cpp
[35m[1mScanning dependencies of target std_msgs_generate_messages_nodejs[0m
[35m[1mScanning dependencies of target sensor_msgs_generate_messages_nodejs[0m
[35m[1mScanning dependencies of target geometry_msgs_generate_messages_nodejs[0m
[  0%] Built target sensor_msgs_generate_messages_nodejs
[  0%] Built target geometry_msgs_generate_messages_nodejs
[  0%] Built target std_msgs_generate_messages_nodejs
[  0%] Built target _rgbd_generate_messages_check_deps_GetRGBD
[35m[1mScanning dependencies of target std_msgs_generate_messages_lisp[0m
[35m[1mScanning dependencies of target sensor_msgs_generate_messages_lisp[0m
[35m[1mScanning dependencies of target geometry_msgs_generate_messages_lisp[0m
[35m[1mScanning dependencies of target sensor_msgs_generate_messages_py[0m
[  0%] Built target sensor_msgs_generate_messages_lisp
[  0%] Built target geometry_msgs_generate_messages_lisp
[  0%] Built target std_msgs_generate_messages_lisp
[35m[1mScanning dependencies of target geometry_msgs_generate_messages_py[0m
[35m[1mScanning dependencies of target std_msgs_generate_messages_py[0m
[  0%] Built target sensor_msgs_generate_messages_py
[35m[1mScanning dependencies of target sensor_msgs_generate_messages_eus[0m
[  0%] Built target geometry_msgs_generate_messages_py
[35m[1mScanning dependencies of target geometry_msgs_generate_messages_eus[0m
[  0%] Built target std_msgs_generate_messages_py
[  0%] Built target sensor_msgs_generate_messages_eus
[35m[1mScanning dependencies of target std_msgs_generate_messages_eus[0m
[  0%] Built target geometry_msgs_generate_messages_eus
[35m[1mScanning dependencies of target rgbd_generate_messages_cpp[0m
[35m[1mScanning dependencies of target rgbd_generate_messages_lisp[0m
[  0%] Built target std_msgs_generate_messages_eus
[35m[1mScanning dependencies of target rgbd_generate_messages_nodejs[0m
[35m[1mScanning dependencies of target rgbd_generate_messages_py[0m
[  1%] [34m[1mGenerating C++ code from rgbd/RGBDMsg.msg[0m
[  3%] [34m[1mGenerating Lisp code from rgbd/RGBDMsg.msg[0m
[  5%] [34m[1mGenerating Javascript code from rgbd/RGBDMsg.msg[0m
[  6%] [34m[1mGenerating Python from MSG rgbd/RGBDMsg[0m
[  8%] [34m[1mGenerating Lisp code from rgbd/GetRGBD.srv[0m
[ 10%] [34m[1mGenerating Javascript code from rgbd/GetRGBD.srv[0m
[ 12%] [34m[1mGenerating Lisp code from rgbd/Project2DTo3D.srv[0m
[ 13%] [34m[1mGenerating Javascript code from rgbd/Project2DTo3D.srv[0m
[ 15%] [34m[1mGenerating Python code from SRV rgbd/GetRGBD[0m
[ 17%] [34m[1mGenerating C++ code from rgbd/GetRGBD.srv[0m
[ 17%] Built target rgbd_generate_messages_lisp
[ 17%] Built target rgbd_generate_messages_nodejs
[35m[1mScanning dependencies of target rgbd_generate_messages_eus[0m
[ 18%] [34m[1mGenerating C++ code from rgbd/Project2DTo3D.srv[0m
[ 20%] [34m[1mGenerating EusLisp code from rgbd/RGBDMsg.msg[0m
[ 22%] [34m[1mGenerating Python code from SRV rgbd/Project2DTo3D[0m
[ 24%] [34m[1mGenerating EusLisp code from rgbd/GetRGBD.srv[0m
[ 25%] [34m[1mGenerating EusLisp code from rgbd/Project2DTo3D.srv[0m
[ 27%] [34m[1mGenerating Python msg __init__.py for rgbd[0m
[ 29%] [34m[1mGenerating EusLisp manifest code for rgbd[0m
[ 31%] [34m[1mGenerating Python srv __init__.py for rgbd[0m
[ 31%] Built target rgbd_generate_messages_cpp
[35m[1mScanning dependencies of target rgbd[0m
[ 31%] Built target rgbd_generate_messages_py
[ 34%] [32mBuilding CXX object CMakeFiles/rgbd.dir/src/server.cpp.o[0m
[ 34%] [32mBuilding CXX object CMakeFiles/rgbd.dir/src/Client.cpp.o[0m
[ 36%] [32mBuilding CXX object CMakeFiles/rgbd.dir/src/ClientRaw.cpp.o[0m
[ 36%] Built target rgbd_generate_messages_eus
[ 37%] [32mBuilding CXX object CMakeFiles/rgbd.dir/src/Image.cpp.o[0m
[ 39%] [32mBuilding CXX object CMakeFiles/rgbd.dir/src/view.cpp.o[0m
[ 41%] [32mBuilding CXX object CMakeFiles/rgbd.dir/src/serialization.cpp.o[0m
[ 43%] [32mBuilding CXX object CMakeFiles/rgbd.dir/src/ros/conversions.cpp.o[0m
[ 44%] [32mBuilding CXX object CMakeFiles/rgbd.dir/src/shared_mem_server.cpp.o[0m
[35m[1mScanning dependencies of target rgbd_generate_messages[0m
[ 44%] Built target rgbd_generate_messages
[ 46%] [32mBuilding CXX object CMakeFiles/rgbd.dir/src/shared_mem_client.cpp.o[0m
[ 48%] [32m[1mLinking CXX shared library /home/amigo/ros/kinetic/system/devel/.private/rgbd/lib/librgbd.so[0m
CMakeFiles/rgbd.dir/src/view.cpp.o: In function `main':
view.cpp:(.text+0x0): multiple definition of `main'
CMakeFiles/rgbd.dir/src/server.cpp.o:server.cpp:(.text+0x721): first defined here
collect2: error: ld returned 1 exit status
CMakeFiles/rgbd.dir/build.make:574: recipe for target '/home/amigo/ros/kinetic/system/devel/.private/rgbd/lib/librgbd.so' failed
make[2]: *** [/home/amigo/ros/kinetic/system/devel/.private/rgbd/lib/librgbd.so] Error 1
make[1]: *** [CMakeFiles/rgbd.dir/all] Error 2
CMakeFiles/Makefile2:252: recipe for target 'CMakeFiles/rgbd.dir/all' failed
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
~~~

Also, it seems that the spelling/capitalization of some files in CMakeLists.txt do not match the files in src. For instance in the rgbd library it references src/Server.cpp and src/View.cpp but these are actually src/server.cpp and src/view.cpp, respectively.

**Comment by smnogar** [comment]
Ah, this has to do with ubuntu being case sensitive and mac is case insensitive. When I cloned the files via the mac they were being thrown out even.

**Comment by LoyVanBeek** [comment]
Still, the casing in CMakelists should just match, I think.

**Comment by MatthijsBurgh** [comment]
You have to take a better look. We have both server.cpp and Server.cpp. One contains the implementation of a class, the other one is an executable. Same for view and View.

**Comment by LoyVanBeek** [comment]
😞
